---
name: Class-Lego
version: 0.001
author: []
abstract: Build your classes with basic building blocks
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Scalar::Defer: 0.13
  Sub::Exporter: 0
  Sub::Install: 0
build_requires:
  Test::More: 0
provides:
  Class::Lego:
    file: lib/Class/Lego.pm
    version: 0.001
  Class::Lego::Myself:
    file: lib/Class/Lego/Myself.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
